# Generated by Django 3.1.2 on 2020-10-16 19:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20201016_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='plants_imgs/'),
        ),
    ]
