# Generated by Django 3.1.2 on 2020-10-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20201016_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantevent',
            old_name='name',
            new_name='event',
        ),
        migrations.AddField(
            model_name='plantevent',
            name='user_plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.userplant'),
            preserve_default=False,
        ),
    ]
