# Generated by Django 3.1.2 on 2020-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plantevent_plant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantevent',
            name='event',
            field=models.CharField(choices=[('watering', 'podlewanie'), ('fertilization', 'nawożenie'), ('transplantation', 'przesadzanie'), ('other', 'inne')], max_length=200),
        ),
    ]
