# Generated by Django 3.1.2 on 2020-10-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20201017_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantevent',
            name='plant_owner',
        ),
    ]
