# Generated by Django 3.1.2 on 2020-10-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_remove_plantevent_plant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='plant',
        ),
        migrations.DeleteModel(
            name='PlantEvent',
        ),
        migrations.DeleteModel(
            name='UserPlant',
        ),
    ]
